### ISSUE TITLE
Add workflows for CodeQL Analysis and Lint Error Description

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-python#14]
We currently don't have a workflow for CodeQL analysis and lint errors. Let's add a new workflow to perform both and document it in README file

- [x] #23
- [x] #36

**Comment by neelam-kushwah** [comment]
I just checked, and it appears that we already have CodeQL enabled for all repositories under the uprotocol project. Therefore, there's no need to add another one. Let's proceed by adding only the linting workflow.
